// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socket.proto

package socket

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type UploadAuctionBody struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadAuctionBody) Reset()         { *m = UploadAuctionBody{} }
func (m *UploadAuctionBody) String() string { return proto.CompactTextString(m) }
func (*UploadAuctionBody) ProtoMessage()    {}
func (*UploadAuctionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{0}
}

func (m *UploadAuctionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadAuctionBody.Unmarshal(m, b)
}
func (m *UploadAuctionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadAuctionBody.Marshal(b, m, deterministic)
}
func (m *UploadAuctionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadAuctionBody.Merge(m, src)
}
func (m *UploadAuctionBody) XXX_Size() int {
	return xxx_messageInfo_UploadAuctionBody.Size(m)
}
func (m *UploadAuctionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadAuctionBody.DiscardUnknown(m)
}

var xxx_messageInfo_UploadAuctionBody proto.InternalMessageInfo

func (m *UploadAuctionBody) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type ListenRoomBody struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRoomBody) Reset()         { *m = ListenRoomBody{} }
func (m *ListenRoomBody) String() string { return proto.CompactTextString(m) }
func (*ListenRoomBody) ProtoMessage()    {}
func (*ListenRoomBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{1}
}

func (m *ListenRoomBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRoomBody.Unmarshal(m, b)
}
func (m *ListenRoomBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRoomBody.Marshal(b, m, deterministic)
}
func (m *ListenRoomBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRoomBody.Merge(m, src)
}
func (m *ListenRoomBody) XXX_Size() int {
	return xxx_messageInfo_ListenRoomBody.Size(m)
}
func (m *ListenRoomBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRoomBody.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRoomBody proto.InternalMessageInfo

func (m *ListenRoomBody) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *ListenRoomBody) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UnregisterRoomBody struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterRoomBody) Reset()         { *m = UnregisterRoomBody{} }
func (m *UnregisterRoomBody) String() string { return proto.CompactTextString(m) }
func (*UnregisterRoomBody) ProtoMessage()    {}
func (*UnregisterRoomBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{2}
}

func (m *UnregisterRoomBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRoomBody.Unmarshal(m, b)
}
func (m *UnregisterRoomBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRoomBody.Marshal(b, m, deterministic)
}
func (m *UnregisterRoomBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRoomBody.Merge(m, src)
}
func (m *UnregisterRoomBody) XXX_Size() int {
	return xxx_messageInfo_UnregisterRoomBody.Size(m)
}
func (m *UnregisterRoomBody) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRoomBody.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRoomBody proto.InternalMessageInfo

func (m *UnregisterRoomBody) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type StopListenRoomBody struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopListenRoomBody) Reset()         { *m = StopListenRoomBody{} }
func (m *StopListenRoomBody) String() string { return proto.CompactTextString(m) }
func (*StopListenRoomBody) ProtoMessage()    {}
func (*StopListenRoomBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{3}
}

func (m *StopListenRoomBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopListenRoomBody.Unmarshal(m, b)
}
func (m *StopListenRoomBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopListenRoomBody.Marshal(b, m, deterministic)
}
func (m *StopListenRoomBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopListenRoomBody.Merge(m, src)
}
func (m *StopListenRoomBody) XXX_Size() int {
	return xxx_messageInfo_StopListenRoomBody.Size(m)
}
func (m *StopListenRoomBody) XXX_DiscardUnknown() {
	xxx_messageInfo_StopListenRoomBody.DiscardUnknown(m)
}

var xxx_messageInfo_StopListenRoomBody proto.InternalMessageInfo

func (m *StopListenRoomBody) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *StopListenRoomBody) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateRoomBody struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auctionId,proto3" json:"auctionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomBody) Reset()         { *m = CreateRoomBody{} }
func (m *CreateRoomBody) String() string { return proto.CompactTextString(m) }
func (*CreateRoomBody) ProtoMessage()    {}
func (*CreateRoomBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{4}
}

func (m *CreateRoomBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomBody.Unmarshal(m, b)
}
func (m *CreateRoomBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomBody.Marshal(b, m, deterministic)
}
func (m *CreateRoomBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomBody.Merge(m, src)
}
func (m *CreateRoomBody) XXX_Size() int {
	return xxx_messageInfo_CreateRoomBody.Size(m)
}
func (m *CreateRoomBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomBody.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomBody proto.InternalMessageInfo

func (m *CreateRoomBody) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UploadAuctionBody)(nil), "socket.UploadAuctionBody")
	proto.RegisterType((*ListenRoomBody)(nil), "socket.ListenRoomBody")
	proto.RegisterType((*UnregisterRoomBody)(nil), "socket.UnregisterRoomBody")
	proto.RegisterType((*StopListenRoomBody)(nil), "socket.StopListenRoomBody")
	proto.RegisterType((*CreateRoomBody)(nil), "socket.CreateRoomBody")
	proto.RegisterType((*Empty)(nil), "socket.Empty")
}

func init() { proto.RegisterFile("socket.proto", fileDescriptor_6b39cc5e3943e1cc) }

var fileDescriptor_6b39cc5e3943e1cc = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0x4f, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x0c, 0xb9, 0x04,
	0x43, 0x0b, 0x72, 0xf2, 0x13, 0x53, 0x1c, 0x4b, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x9c, 0xf2, 0x53,
	0x2a, 0x85, 0x64, 0xb8, 0x38, 0x13, 0x21, 0x5c, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x84, 0x80, 0x92, 0x1b, 0x17, 0x9f, 0x4f, 0x66, 0x71, 0x49, 0x6a, 0x5e, 0x50, 0x7e, 0x7e,
	0x2e, 0x61, 0xf5, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x4c, 0x60,
	0x29, 0x28, 0x4f, 0xc9, 0x88, 0x4b, 0x28, 0x34, 0xaf, 0x28, 0x35, 0x1d, 0x64, 0x56, 0x11, 0x71,
	0x66, 0x29, 0x79, 0x71, 0x09, 0x05, 0x97, 0xe4, 0x17, 0x50, 0xc5, 0x7e, 0x3d, 0x2e, 0x3e, 0xe7,
	0xa2, 0xd4, 0xc4, 0x92, 0x54, 0x22, 0xed, 0x66, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x34,
	0xda, 0xc8, 0xc4, 0xc5, 0x16, 0x0c, 0x0e, 0x3e, 0x21, 0x6b, 0x2e, 0x5e, 0x94, 0xe0, 0x13, 0x92,
	0xd4, 0x83, 0x06, 0x33, 0x46, 0xa8, 0x4a, 0xf1, 0xc2, 0xa4, 0xc0, 0xa6, 0x28, 0x31, 0x08, 0x99,
	0x72, 0x71, 0x21, 0x3c, 0x22, 0x24, 0x06, 0x93, 0x46, 0xf5, 0x1c, 0xa6, 0x36, 0x5b, 0x2e, 0x3e,
	0xd4, 0x70, 0x13, 0x92, 0x82, 0x5b, 0x8a, 0x11, 0x9e, 0x58, 0xb5, 0xa3, 0x06, 0x21, 0x42, 0x3b,
	0x66, 0xd0, 0x62, 0x75, 0x34, 0x22, 0xd4, 0x10, 0x8e, 0x46, 0x0d, 0x49, 0x0c, 0x6d, 0x49, 0x6c,
	0xe0, 0x64, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x60, 0xf2, 0xdf, 0x43, 0x86, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SocketClient is the client API for Socket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocketClient interface {
	// Sends a greeting
	UploadAuction(ctx context.Context, in *UploadAuctionBody, opts ...grpc.CallOption) (*Empty, error)
	ListenRoom(ctx context.Context, in *ListenRoomBody, opts ...grpc.CallOption) (*Empty, error)
	UnregisterRoom(ctx context.Context, in *UnregisterRoomBody, opts ...grpc.CallOption) (*Empty, error)
	StopListenRoom(ctx context.Context, in *StopListenRoomBody, opts ...grpc.CallOption) (*Empty, error)
	CreateRoom(ctx context.Context, in *CreateRoomBody, opts ...grpc.CallOption) (*Empty, error)
}

type socketClient struct {
	cc *grpc.ClientConn
}

func NewSocketClient(cc *grpc.ClientConn) SocketClient {
	return &socketClient{cc}
}

func (c *socketClient) UploadAuction(ctx context.Context, in *UploadAuctionBody, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/socket.Socket/UploadAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) ListenRoom(ctx context.Context, in *ListenRoomBody, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/socket.Socket/ListenRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) UnregisterRoom(ctx context.Context, in *UnregisterRoomBody, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/socket.Socket/UnregisterRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) StopListenRoom(ctx context.Context, in *StopListenRoomBody, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/socket.Socket/StopListenRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) CreateRoom(ctx context.Context, in *CreateRoomBody, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/socket.Socket/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocketServer is the server API for Socket service.
type SocketServer interface {
	// Sends a greeting
	UploadAuction(context.Context, *UploadAuctionBody) (*Empty, error)
	ListenRoom(context.Context, *ListenRoomBody) (*Empty, error)
	UnregisterRoom(context.Context, *UnregisterRoomBody) (*Empty, error)
	StopListenRoom(context.Context, *StopListenRoomBody) (*Empty, error)
	CreateRoom(context.Context, *CreateRoomBody) (*Empty, error)
}

// UnimplementedSocketServer can be embedded to have forward compatible implementations.
type UnimplementedSocketServer struct {
}

func (*UnimplementedSocketServer) UploadAuction(ctx context.Context, req *UploadAuctionBody) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAuction not implemented")
}
func (*UnimplementedSocketServer) ListenRoom(ctx context.Context, req *ListenRoomBody) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenRoom not implemented")
}
func (*UnimplementedSocketServer) UnregisterRoom(ctx context.Context, req *UnregisterRoomBody) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterRoom not implemented")
}
func (*UnimplementedSocketServer) StopListenRoom(ctx context.Context, req *StopListenRoomBody) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopListenRoom not implemented")
}
func (*UnimplementedSocketServer) CreateRoom(ctx context.Context, req *CreateRoomBody) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}

func RegisterSocketServer(s *grpc.Server, srv SocketServer) {
	s.RegisterService(&_Socket_serviceDesc, srv)
}

func _Socket_UploadAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAuctionBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).UploadAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/UploadAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).UploadAuction(ctx, req.(*UploadAuctionBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_ListenRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenRoomBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).ListenRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/ListenRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).ListenRoom(ctx, req.(*ListenRoomBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_UnregisterRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRoomBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).UnregisterRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/UnregisterRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).UnregisterRoom(ctx, req.(*UnregisterRoomBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_StopListenRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopListenRoomBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).StopListenRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/StopListenRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).StopListenRoom(ctx, req.(*StopListenRoomBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).CreateRoom(ctx, req.(*CreateRoomBody))
	}
	return interceptor(ctx, in, info, handler)
}

var _Socket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socket.Socket",
	HandlerType: (*SocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadAuction",
			Handler:    _Socket_UploadAuction_Handler,
		},
		{
			MethodName: "ListenRoom",
			Handler:    _Socket_ListenRoom_Handler,
		},
		{
			MethodName: "UnregisterRoom",
			Handler:    _Socket_UnregisterRoom_Handler,
		},
		{
			MethodName: "StopListenRoom",
			Handler:    _Socket_StopListenRoom_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _Socket_CreateRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "socket.proto",
}
